[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "secs-inference"
version = "0.1.0"
requires-python = ">=3.11, <3.13"
dependencies = [
  "numpy",
  "omegaconf",
  "safetensors",
  "secs",
  "torch",
]

[tool.uv.sources]
secs = { path = "secs" }

[tool.setuptools.packages.find]
where = ["src"]
