"""Generated provider Problem wire facts; do not edit."""
OPENAPI_SHA256 = '9204d102edec5dc66bc7c59d2ba4beaab50e93060d9e80f0e51a757abfa19af6'
EVIDENCE = {'detail': {'maxLength': 1024,
            'minLength': 1,
            'not': {'pattern': '^[\\u0020\\u00a0\\u1680\\u2000-\\u200a\\u202f\\u205f\\u3000]|[\\u0020\\u00a0\\u1680\\u2000-\\u200a\\u202f\\u205f\\u3000](?![\\s\\S])|[\\u0000-\\u001f\\u007f-\\u009f\\u00ad\\u061c\\u200b-\\u200f\\u2028-\\u202e\\u2060-\\u206f\\ud800-\\udfff\\ufeff\\ufff9-\\ufffb]'},
            'type': 'string',
            'x-nmr-max-utf8-bytes': 1024},
 'instance': {'maxLength': 404, 'minLength': 1, 'type': 'string'},
 'request_id': {'maxLength': 128,
                'minLength': 1,
                'pattern': '^[\\u0021-\\u007e]+(?![\\s\\S])',
                'type': 'string'}}
OPERATIONS = {'execution_attempt_complete': {400: (8,),
                                401: (1,),
                                403: (2,),
                                404: (9,),
                                408: (3,),
                                409: (10,),
                                413: (11,),
                                414: (4,),
                                431: (5,),
                                500: (6,),
                                503: (12, 7)},
 'execution_attempt_fail': {400: (8,),
                            401: (1,),
                            403: (2,),
                            404: (9,),
                            408: (3,),
                            409: (10,),
                            413: (11,),
                            414: (4,),
                            431: (5,),
                            500: (6,),
                            503: (12, 7)},
 'execution_attempt_progress': {400: (8,),
                                401: (1,),
                                403: (2,),
                                404: (9,),
                                408: (3,),
                                409: (10,),
                                413: (11,),
                                414: (4,),
                                431: (5,),
                                500: (6,),
                                503: (12, 7)},
 'execution_attempt_read': {400: (13,),
                            401: (1,),
                            403: (2,),
                            404: (9,),
                            408: (3,),
                            414: (4,),
                            431: (5,),
                            500: (6,),
                            503: (7,)},
 'execution_attempt_start': {400: (8,),
                             401: (1,),
                             403: (2,),
                             404: (9,),
                             408: (3,),
                             409: (10,),
                             413: (11,),
                             414: (4,),
                             431: (5,),
                             500: (6,),
                             503: (12, 7)},
 'execution_attempts_list': {400: (0,),
                             401: (1,),
                             403: (2,),
                             408: (3,),
                             414: (4,),
                             431: (5,),
                             500: (6,),
                             503: (7,)},
 'job_input_read': {400: (0,),
                    401: (1,),
                    403: (2,),
                    404: (9,),
                    408: (3,),
                    414: (4,),
                    431: (5,),
                    500: (6,),
                    503: (7,)},
 'job_upload_read_capability': {400: (13,),
                                401: (1,),
                                403: (2,),
                                404: (9,),
                                408: (3,),
                                409: (10,),
                                414: (4,),
                                431: (5,),
                                500: (6,),
                                503: (12, 7)},
 'job_upload_set_read': {400: (13,),
                         401: (1,),
                         403: (2,),
                         404: (9,),
                         408: (3,),
                         414: (4,),
                         431: (5,),
                         500: (6,),
                         503: (7,)},
 'jobs_list': {400: (0,),
               401: (1,),
               403: (2,),
               408: (3,),
               414: (4,),
               431: (5,),
               500: (6,),
               503: (7,)},
 'provider_hello': {400: (8,),
                    401: (1,),
                    403: (2,),
                    404: (9,),
                    408: (3,),
                    413: (11,),
                    414: (4,),
                    431: (5,),
                    500: (6,),
                    503: (12, 7)}}
PROFILES = ({'fixed_details': {},
  'properties': {'code': {'enum': ['provider_request_invalid', 'request_content_not_supported']},
                 'detail': {'maxLength': 1024,
                            'minLength': 1,
                            'not': {'pattern': '^[\\u0020\\u00a0\\u1680\\u2000-\\u200a\\u202f\\u205f\\u3000]|[\\u0020\\u00a0\\u1680\\u2000-\\u200a\\u202f\\u205f\\u3000](?![\\s\\S])|[\\u0000-\\u001f\\u007f-\\u009f\\u00ad\\u061c\\u200b-\\u200f\\u2028-\\u202e\\u2060-\\u206f\\ud800-\\udfff\\ufeff\\ufff9-\\ufffb]'},
                            'type': 'string',
                            'x-nmr-max-utf8-bytes': 1024},
                 'instance': {'maxLength': 404, 'minLength': 1, 'type': 'string'},
                 'request_id': {'maxLength': 128,
                                'minLength': 1,
                                'pattern': '^[\\u0021-\\u007e]+(?![\\s\\S])',
                                'type': 'string'},
                 'status': {'const': 400},
                 'title': {'const': 'Bad request'},
                 'type': {'const': 'urn:nmr-api:problem:bad-request'}},
  'upload_codes': ()},
 {'fixed_details': {},
  'properties': {'code': {'enum': ['authentication_failed',
                                   'authentication_nonce_reused',
                                   'authentication_window_closed',
                                   'signature_expired',
                                   'signature_created_in_future']},
                 'detail': {'maxLength': 1024,
                            'minLength': 1,
                            'not': {'pattern': '^[\\u0020\\u00a0\\u1680\\u2000-\\u200a\\u202f\\u205f\\u3000]|[\\u0020\\u00a0\\u1680\\u2000-\\u200a\\u202f\\u205f\\u3000](?![\\s\\S])|[\\u0000-\\u001f\\u007f-\\u009f\\u00ad\\u061c\\u200b-\\u200f\\u2028-\\u202e\\u2060-\\u206f\\ud800-\\udfff\\ufeff\\ufff9-\\ufffb]'},
                            'type': 'string',
                            'x-nmr-max-utf8-bytes': 1024},
                 'instance': {'maxLength': 404, 'minLength': 1, 'type': 'string'},
                 'request_id': {'maxLength': 128,
                                'minLength': 1,
                                'pattern': '^[\\u0021-\\u007e]+(?![\\s\\S])',
                                'type': 'string'},
                 'status': {'const': 401},
                 'title': {'const': 'Request authentication failed'},
                 'type': {'const': 'urn:nmr-api:problem:authentication-failed'}},
  'upload_codes': ()},
 {'fixed_details': {},
  'properties': {'code': {'enum': ['authorization_denied']},
                 'detail': {'maxLength': 1024,
                            'minLength': 1,
                            'not': {'pattern': '^[\\u0020\\u00a0\\u1680\\u2000-\\u200a\\u202f\\u205f\\u3000]|[\\u0020\\u00a0\\u1680\\u2000-\\u200a\\u202f\\u205f\\u3000](?![\\s\\S])|[\\u0000-\\u001f\\u007f-\\u009f\\u00ad\\u061c\\u200b-\\u200f\\u2028-\\u202e\\u2060-\\u206f\\ud800-\\udfff\\ufeff\\ufff9-\\ufffb]'},
                            'type': 'string',
                            'x-nmr-max-utf8-bytes': 1024},
                 'instance': {'maxLength': 404, 'minLength': 1, 'type': 'string'},
                 'request_id': {'maxLength': 128,
                                'minLength': 1,
                                'pattern': '^[\\u0021-\\u007e]+(?![\\s\\S])',
                                'type': 'string'},
                 'status': {'const': 403},
                 'title': {'const': 'Authorization denied'},
                 'type': {'const': 'urn:nmr-api:problem:authorization-denied'}},
  'upload_codes': ()},
 {'fixed_details': {},
  'properties': {'code': {'enum': ['request_body_timeout']},
                 'detail': {'maxLength': 1024,
                            'minLength': 1,
                            'not': {'pattern': '^[\\u0020\\u00a0\\u1680\\u2000-\\u200a\\u202f\\u205f\\u3000]|[\\u0020\\u00a0\\u1680\\u2000-\\u200a\\u202f\\u205f\\u3000](?![\\s\\S])|[\\u0000-\\u001f\\u007f-\\u009f\\u00ad\\u061c\\u200b-\\u200f\\u2028-\\u202e\\u2060-\\u206f\\ud800-\\udfff\\ufeff\\ufff9-\\ufffb]'},
                            'type': 'string',
                            'x-nmr-max-utf8-bytes': 1024},
                 'instance': {'maxLength': 404, 'minLength': 1, 'type': 'string'},
                 'request_id': {'maxLength': 128,
                                'minLength': 1,
                                'pattern': '^[\\u0021-\\u007e]+(?![\\s\\S])',
                                'type': 'string'},
                 'status': {'const': 408},
                 'title': {'const': 'Request body timeout'},
                 'type': {'const': 'urn:nmr-api:problem:request-body-timeout'}},
  'upload_codes': ()},
 {'fixed_details': {},
  'properties': {'code': {'enum': ['request_path_too_large', 'request_query_too_large']},
                 'detail': {'maxLength': 1024,
                            'minLength': 1,
                            'not': {'pattern': '^[\\u0020\\u00a0\\u1680\\u2000-\\u200a\\u202f\\u205f\\u3000]|[\\u0020\\u00a0\\u1680\\u2000-\\u200a\\u202f\\u205f\\u3000](?![\\s\\S])|[\\u0000-\\u001f\\u007f-\\u009f\\u00ad\\u061c\\u200b-\\u200f\\u2028-\\u202e\\u2060-\\u206f\\ud800-\\udfff\\ufeff\\ufff9-\\ufffb]'},
                            'type': 'string',
                            'x-nmr-max-utf8-bytes': 1024},
                 'instance': {'maxLength': 404, 'minLength': 1, 'type': 'string'},
                 'request_id': {'maxLength': 128,
                                'minLength': 1,
                                'pattern': '^[\\u0021-\\u007e]+(?![\\s\\S])',
                                'type': 'string'},
                 'status': {'const': 414},
                 'title': {'const': 'URI too long'},
                 'type': {'const': 'urn:nmr-api:problem:uri-too-long'}},
  'upload_codes': ()},
 {'fixed_details': {},
  'properties': {'code': {'enum': ['request_header_bytes_too_large',
                                   'request_header_count_too_large']},
                 'detail': {'maxLength': 1024,
                            'minLength': 1,
                            'not': {'pattern': '^[\\u0020\\u00a0\\u1680\\u2000-\\u200a\\u202f\\u205f\\u3000]|[\\u0020\\u00a0\\u1680\\u2000-\\u200a\\u202f\\u205f\\u3000](?![\\s\\S])|[\\u0000-\\u001f\\u007f-\\u009f\\u00ad\\u061c\\u200b-\\u200f\\u2028-\\u202e\\u2060-\\u206f\\ud800-\\udfff\\ufeff\\ufff9-\\ufffb]'},
                            'type': 'string',
                            'x-nmr-max-utf8-bytes': 1024},
                 'instance': {'maxLength': 404, 'minLength': 1, 'type': 'string'},
                 'request_id': {'maxLength': 128,
                                'minLength': 1,
                                'pattern': '^[\\u0021-\\u007e]+(?![\\s\\S])',
                                'type': 'string'},
                 'status': {'const': 431},
                 'title': {'const': 'Request header fields too large'},
                 'type': {'const': 'urn:nmr-api:problem:request-header-fields-too-large'}},
  'upload_codes': ()},
 {'fixed_details': {},
  'properties': {'code': {'enum': ['internal_error',
                                   'response_validation_failed',
                                   'response_size_limit_exceeded',
                                   'http_route_memory_budget_too_small',
                                   'request_signature_processing_failed',
                                   'upload_finalize_length_mismatch',
                                   'upload_finalize_committed_facts_mismatch',
                                   'upload_finalize_storage_integrity_failed',
                                   'upload_finalize_storage_token_creation_failed',
                                   'upload_finalize_storage_response_invalid',
                                   'upload_finalize_storage_error_json_invalid',
                                   'upload_finalize_storage_error_fields_invalid',
                                   'upload_finalize_storage_error_contract_mismatch',
                                   'upload_finalize_storage_request_invalid',
                                   'job_open_inputs_inconsistent']},
                 'detail': {'maxLength': 1024,
                            'minLength': 1,
                            'not': {'pattern': '^[\\u0020\\u00a0\\u1680\\u2000-\\u200a\\u202f\\u205f\\u3000]|[\\u0020\\u00a0\\u1680\\u2000-\\u200a\\u202f\\u205f\\u3000](?![\\s\\S])|[\\u0000-\\u001f\\u007f-\\u009f\\u00ad\\u061c\\u200b-\\u200f\\u2028-\\u202e\\u2060-\\u206f\\ud800-\\udfff\\ufeff\\ufff9-\\ufffb]'},
                            'type': 'string',
                            'x-nmr-max-utf8-bytes': 1024},
                 'instance': {'maxLength': 404, 'minLength': 1, 'type': 'string'},
                 'request_id': {'maxLength': 128,
                                'minLength': 1,
                                'pattern': '^[\\u0021-\\u007e]+(?![\\s\\S])',
                                'type': 'string'},
                 'status': {'const': 500},
                 'title': {'const': 'Internal server error'},
                 'type': {'const': 'urn:nmr-api:problem:internal-error'}},
  'upload_codes': ()},
 {'fixed_details': {'http_exchange_count_exhausted': 'This server has reached its limit for '
                                                     'simultaneous requests. This attempt was '
                                                     'rejected before the operation started; it '
                                                     'made no changes. Wait briefly, then try '
                                                     'again.',
                    'http_exchange_memory_budget_exhausted': "This server's memory limit for "
                                                             'requests prevents it from accepting '
                                                             'another request. This attempt was '
                                                             'rejected before the operation '
                                                             'started; it made no changes. Wait '
                                                             'briefly, then try again.',
                    'http_exchange_runtime_not_accepting': 'This server is currently not accepting '
                                                           'new requests. This attempt was '
                                                           'rejected before the operation started; '
                                                           'it made no changes. Try again later.'},
  'properties': {'code': {'enum': ['service_unavailable',
                                   'upload_finalize_storage_authorization_rejected',
                                   'stored_analysis_result_inconsistent',
                                   'http_exchange_deadline_exceeded',
                                   'authentication_replay_ledger_unavailable',
                                   'request_signature_verifier_unavailable',
                                   'database_connection_preparation_failed',
                                   'database_executor_quarantined',
                                   'database_work_admission_stopped',
                                   'database_work_slots_exhausted',
                                   'job_create_reference_exhausted',
                                   'job_create_randomness_unavailable',
                                   'job_state_update_randomness_unavailable',
                                   'job_upload_set_randomness_unavailable',
                                   'job_provider_selection_randomness_unavailable',
                                   'description_update_randomness_unavailable',
                                   'job_mutation_clock_behind',
                                   'upload_capability_clock_behind',
                                   'upload_capability_expired_before_commit',
                                   'upload_capability_randomness_unavailable',
                                   'upload_capability_generation_failed',
                                   'job_cancellation_randomness_unavailable',
                                   'job_deletion_randomness_unavailable',
                                   'upload_finalize_randomness_unavailable',
                                   'upload_finalize_clock_behind',
                                   'upload_create_randomness_unavailable',
                                   'upload_create_reference_exhausted',
                                   'project_description_clock_behind',
                                   'upload_description_clock_behind',
                                   'upload_deletion_clock_behind',
                                   'execution_attempt_start_randomness_unavailable',
                                   'execution_attempt_start_reference_exhausted',
                                   'execution_attempt_start_clock_behind',
                                   'execution_attempt_progress_clock_behind',
                                   'execution_attempt_outcome_clock_behind',
                                   'project_list_details_unavailable',
                                   'analysis_kind_list_inactive_selection',
                                   'analysis_kind_list_missing_selection',
                                   'analysis_provider_list_selection_unavailable',
                                   'analysis_provider_list_selection_changed',
                                   'provider_directory_clock_behind',
                                   'provider_execution_attempt_capacity_exhausted',
                                   'http_route_memory_capacity_exhausted',
                                   'authentication_replay_capacity_exhausted',
                                   'upload_finalize_storage_connection_timeout',
                                   'upload_finalize_storage_request_timeout',
                                   'upload_finalize_storage_request_idle_timeout',
                                   'upload_finalize_storage_communication_failed',
                                   'upload_finalize_storage_admission_stopped',
                                   'upload_finalize_storage_slots_exhausted',
                                   'upload_finalize_storage_cleanup_unconfirmed',
                                   'upload_finalize_storage_deadline_exceeded',
                                   'upload_finalize_storage_completed_late',
                                   'database_lock_unavailable',
                                   'database_query_canceled',
                                   'database_idle_transaction_timeout',
                                   'http_exchange_count_exhausted',
                                   'http_exchange_memory_budget_exhausted',
                                   'http_exchange_runtime_not_accepting']},
                 'detail': {'maxLength': 1024,
                            'minLength': 1,
                            'not': {'pattern': '^[\\u0020\\u00a0\\u1680\\u2000-\\u200a\\u202f\\u205f\\u3000]|[\\u0020\\u00a0\\u1680\\u2000-\\u200a\\u202f\\u205f\\u3000](?![\\s\\S])|[\\u0000-\\u001f\\u007f-\\u009f\\u00ad\\u061c\\u200b-\\u200f\\u2028-\\u202e\\u2060-\\u206f\\ud800-\\udfff\\ufeff\\ufff9-\\ufffb]'},
                            'type': 'string',
                            'x-nmr-max-utf8-bytes': 1024},
                 'instance': {'maxLength': 404, 'minLength': 1, 'type': 'string'},
                 'request_id': {'maxLength': 128,
                                'minLength': 1,
                                'pattern': '^[\\u0021-\\u007e]+(?![\\s\\S])',
                                'type': 'string'},
                 'status': {'const': 503},
                 'title': {'const': 'Service unavailable'},
                 'type': {'const': 'urn:nmr-api:problem:service-unavailable'}},
  'upload_codes': ()},
 {'fixed_details': {},
  'properties': {'code': {'enum': ['provider_request_invalid', 'request_query_not_supported']},
                 'detail': {'maxLength': 1024,
                            'minLength': 1,
                            'not': {'pattern': '^[\\u0020\\u00a0\\u1680\\u2000-\\u200a\\u202f\\u205f\\u3000]|[\\u0020\\u00a0\\u1680\\u2000-\\u200a\\u202f\\u205f\\u3000](?![\\s\\S])|[\\u0000-\\u001f\\u007f-\\u009f\\u00ad\\u061c\\u200b-\\u200f\\u2028-\\u202e\\u2060-\\u206f\\ud800-\\udfff\\ufeff\\ufff9-\\ufffb]'},
                            'type': 'string',
                            'x-nmr-max-utf8-bytes': 1024},
                 'instance': {'maxLength': 404, 'minLength': 1, 'type': 'string'},
                 'request_id': {'maxLength': 128,
                                'minLength': 1,
                                'pattern': '^[\\u0021-\\u007e]+(?![\\s\\S])',
                                'type': 'string'},
                 'status': {'const': 400},
                 'title': {'const': 'Bad request'},
                 'type': {'const': 'urn:nmr-api:problem:bad-request'}},
  'upload_codes': ()},
 {'fixed_details': {},
  'properties': {'code': {'enum': ['resource_not_found']},
                 'detail': {'maxLength': 1024,
                            'minLength': 1,
                            'not': {'pattern': '^[\\u0020\\u00a0\\u1680\\u2000-\\u200a\\u202f\\u205f\\u3000]|[\\u0020\\u00a0\\u1680\\u2000-\\u200a\\u202f\\u205f\\u3000](?![\\s\\S])|[\\u0000-\\u001f\\u007f-\\u009f\\u00ad\\u061c\\u200b-\\u200f\\u2028-\\u202e\\u2060-\\u206f\\ud800-\\udfff\\ufeff\\ufff9-\\ufffb]'},
                            'type': 'string',
                            'x-nmr-max-utf8-bytes': 1024},
                 'instance': {'maxLength': 404, 'minLength': 1, 'type': 'string'},
                 'request_id': {'maxLength': 128,
                                'minLength': 1,
                                'pattern': '^[\\u0021-\\u007e]+(?![\\s\\S])',
                                'type': 'string'},
                 'status': {'const': 404},
                 'title': {'const': 'Resource not found'},
                 'type': {'const': 'urn:nmr-api:problem:not-found'}},
  'upload_codes': ()},
 {'fixed_details': {},
  'properties': {'code': {'enum': ['operation_conflict',
                                   'execution_attempt_progress_terminal',
                                   'execution_attempt_progress_regression',
                                   'execution_attempt_completion_after_failure',
                                   'execution_attempt_failure_after_success',
                                   'execution_attempt_failure_replay_mismatch',
                                   'execution_attempt_completion_replay_mismatch',
                                   'execution_attempt_outcome_expired',
                                   'operation_reference_conflict',
                                   'provider_attempt_key_conflict',
                                   'job_provider_attempt_limit_reached',
                                   'job_attempt_limit_reached',
                                   'project_purge_in_progress',
                                   'project_job_limit_reached',
                                   'project_operation_record_limit_reached',
                                   'upload_byte_length_limit_exceeded',
                                   'project_upload_record_limit_reached',
                                   'project_upload_reserved_bytes_limit_exceeded',
                                   'deployment_upload_record_limit_reached',
                                   'deployment_upload_reserved_bytes_limit_exceeded',
                                   'job_state_change_cancelled',
                                   'job_open_pending_uploads',
                                   'upload_linked_to_job',
                                   'upload_finalize_bytes_absent',
                                   'upload_finalize_bytes_incomplete',
                                   'upload_finalize_removal_scheduled',
                                   'job_upload_selection_pending',
                                   'job_upload_selection_cancelled',
                                   'job_upload_selection_retention_expired',
                                   'job_upload_selection_removal_scheduled',
                                   'upload_publish_already_finalized',
                                   'upload_publish_removal_scheduled',
                                   'upload_read_removal_scheduled',
                                   'upload_read_not_finalized']},
                 'detail': {'maxLength': 1024,
                            'minLength': 1,
                            'not': {'pattern': '^[\\u0020\\u00a0\\u1680\\u2000-\\u200a\\u202f\\u205f\\u3000]|[\\u0020\\u00a0\\u1680\\u2000-\\u200a\\u202f\\u205f\\u3000](?![\\s\\S])|[\\u0000-\\u001f\\u007f-\\u009f\\u00ad\\u061c\\u200b-\\u200f\\u2028-\\u202e\\u2060-\\u206f\\ud800-\\udfff\\ufeff\\ufff9-\\ufffb]'},
                            'type': 'string',
                            'x-nmr-max-utf8-bytes': 1024},
                 'instance': {'maxLength': 404, 'minLength': 1, 'type': 'string'},
                 'request_id': {'maxLength': 128,
                                'minLength': 1,
                                'pattern': '^[\\u0021-\\u007e]+(?![\\s\\S])',
                                'type': 'string'},
                 'status': {'const': 409},
                 'title': {'const': 'Operation conflict'},
                 'type': {'const': 'urn:nmr-api:problem:operation-conflict'},
                 'upload_ref': {'description': 'One newly selected Upload rejected by this '
                                               'request; other inputs may also be ineligible.',
                                'pattern': '^upload:sha256:[0-9a-f]{64}(?![\\s\\S])',
                                'type': 'string'}},
  'upload_codes': ('job_upload_selection_retention_expired',
                   'job_upload_selection_removal_scheduled',
                   'job_upload_selection_pending')},
 {'fixed_details': {},
  'properties': {'code': {'enum': ['request_content_too_large']},
                 'detail': {'maxLength': 1024,
                            'minLength': 1,
                            'not': {'pattern': '^[\\u0020\\u00a0\\u1680\\u2000-\\u200a\\u202f\\u205f\\u3000]|[\\u0020\\u00a0\\u1680\\u2000-\\u200a\\u202f\\u205f\\u3000](?![\\s\\S])|[\\u0000-\\u001f\\u007f-\\u009f\\u00ad\\u061c\\u200b-\\u200f\\u2028-\\u202e\\u2060-\\u206f\\ud800-\\udfff\\ufeff\\ufff9-\\ufffb]'},
                            'type': 'string',
                            'x-nmr-max-utf8-bytes': 1024},
                 'instance': {'maxLength': 404, 'minLength': 1, 'type': 'string'},
                 'request_id': {'maxLength': 128,
                                'minLength': 1,
                                'pattern': '^[\\u0021-\\u007e]+(?![\\s\\S])',
                                'type': 'string'},
                 'status': {'const': 413},
                 'title': {'const': 'Request content too large'},
                 'type': {'const': 'urn:nmr-api:problem:request-content-too-large'}},
  'upload_codes': ()},
 {'fixed_details': {},
  'properties': {'code': {'enum': ['service_unavailable', 'http_exchange_deadline_exceeded']},
                 'detail': {'maxLength': 1024,
                            'minLength': 1,
                            'not': {'pattern': '^[\\u0020\\u00a0\\u1680\\u2000-\\u200a\\u202f\\u205f\\u3000]|[\\u0020\\u00a0\\u1680\\u2000-\\u200a\\u202f\\u205f\\u3000](?![\\s\\S])|[\\u0000-\\u001f\\u007f-\\u009f\\u00ad\\u061c\\u200b-\\u200f\\u2028-\\u202e\\u2060-\\u206f\\ud800-\\udfff\\ufeff\\ufff9-\\ufffb]'},
                            'type': 'string',
                            'x-nmr-max-utf8-bytes': 1024},
                 'instance': {'maxLength': 404, 'minLength': 1, 'type': 'string'},
                 'request_id': {'maxLength': 128,
                                'minLength': 1,
                                'pattern': '^[\\u0021-\\u007e]+(?![\\s\\S])',
                                'type': 'string'},
                 'status': {'const': 503},
                 'title': {'const': 'Change outcome unconfirmed'},
                 'type': {'const': 'urn:nmr-api:problem:mutation-outcome-unconfirmed'}},
  'upload_codes': ()},
 {'fixed_details': {},
  'properties': {'code': {'enum': ['provider_request_invalid',
                                   'request_content_not_supported',
                                   'request_query_not_supported']},
                 'detail': {'maxLength': 1024,
                            'minLength': 1,
                            'not': {'pattern': '^[\\u0020\\u00a0\\u1680\\u2000-\\u200a\\u202f\\u205f\\u3000]|[\\u0020\\u00a0\\u1680\\u2000-\\u200a\\u202f\\u205f\\u3000](?![\\s\\S])|[\\u0000-\\u001f\\u007f-\\u009f\\u00ad\\u061c\\u200b-\\u200f\\u2028-\\u202e\\u2060-\\u206f\\ud800-\\udfff\\ufeff\\ufff9-\\ufffb]'},
                            'type': 'string',
                            'x-nmr-max-utf8-bytes': 1024},
                 'instance': {'maxLength': 404, 'minLength': 1, 'type': 'string'},
                 'request_id': {'maxLength': 128,
                                'minLength': 1,
                                'pattern': '^[\\u0021-\\u007e]+(?![\\s\\S])',
                                'type': 'string'},
                 'status': {'const': 400},
                 'title': {'const': 'Bad request'},
                 'type': {'const': 'urn:nmr-api:problem:bad-request'}},
  'upload_codes': ()})
