"""Load a frontend oracle only when it matches the current pinned producer."""

from hashlib import sha256
import json
import os
from pathlib import Path


REFERENCE_LOCK = Path("/contracts/upstream/frontend_reference.json")


def load_frontend_reference(path: Path) -> dict:
    document = json.loads(path.read_text())
    lock_id = f"sha256:{sha256(REFERENCE_LOCK.read_bytes()).hexdigest()}"
    if document.get("reference_lock") != lock_id:
        raise ValueError(f"Frontend reference {path.name} was generated from a different reference lock.")
    build_id = os.environ.get("FRONTEND_REFERENCE_BUILD_ID")
    if document.get("reference_build") != build_id:
        raise ValueError(f"Frontend reference {path.name} was generated by a different reference producer.")
    return document
