#!/usr/bin/env python3
"""Validate and identify the pinned frontend reference environment."""

from __future__ import annotations

import argparse
from hashlib import sha256
import json
from pathlib import Path
import re
from urllib.parse import urlparse


LOCK_RELATIVE_PATH = Path("contracts/upstream/frontend_reference.json")
COMMON_PRODUCER_INPUTS = (
    LOCK_RELATIVE_PATH,
    Path("containers/frontend-reference/Dockerfile"),
    Path("containers/frontend-reference/Dockerfile.dockerignore"),
)
PRODUCER_INPUTS = {
    "frontend": COMMON_PRODUCER_INPUTS + (Path("tools/generate_frontend_reference.ts"),),
    "input": COMMON_PRODUCER_INPUTS + (
        Path("tools/generate_input_fixtures.mjs"),
        Path("tools/generate_nmrium_fixtures.mjs"),
    ),
}
IMAGE_INPUTS = COMMON_PRODUCER_INPUTS + tuple(
    path for paths in PRODUCER_INPUTS.values() for path in paths if path not in COMMON_PRODUCER_INPUTS
)
LOCK_KEYS = {"node_image", "repository", "revision", "schema_id"}


def load_lock(path: Path) -> tuple[dict, bytes]:
    contents = path.read_bytes()
    try:
        document = json.loads(contents)
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise ValueError(f"Cannot read frontend reference lock {path}: expected UTF-8 JSON.") from error
    if not isinstance(document, dict) or set(document) != LOCK_KEYS:
        raise ValueError(
            f"Cannot read frontend reference lock {path}: expected exactly {sorted(LOCK_KEYS)}."
        )
    if not all(isinstance(document[field], str) for field in LOCK_KEYS):
        raise ValueError(f"Cannot read frontend reference lock {path}: every field must be a string.")
    if document["schema_id"] != "secs.frontend-reference-lock.v1":
        raise ValueError(f"Cannot read frontend reference lock {path}: unsupported schema_id.")
    if not re.fullmatch(r"[0-9a-f]{40}", document["revision"]):
        raise ValueError(f"Cannot read frontend reference lock {path}: revision must be a lowercase Git object ID.")
    if not re.fullmatch(r"[^\s]+@sha256:[0-9a-f]{64}", document["node_image"]):
        raise ValueError(f"Cannot read frontend reference lock {path}: node_image must include a SHA-256 digest.")
    repository = urlparse(document["repository"])
    if repository.scheme != "https" or not repository.netloc or not repository.path:
        raise ValueError(f"Cannot read frontend reference lock {path}: repository must be an HTTPS URL.")
    return document, contents


def lock_id(contents: bytes) -> str:
    return f"sha256:{sha256(contents).hexdigest()}"


def content_id(root: Path, relative_paths: tuple[Path, ...]) -> str:
    digest = sha256()
    for relative_path in relative_paths:
        contents = (root / relative_path).read_bytes()
        label = relative_path.as_posix().encode()
        digest.update(len(label).to_bytes(4, "big"))
        digest.update(label)
        digest.update(len(contents).to_bytes(8, "big"))
        digest.update(contents)
    return f"sha256:{digest.hexdigest()}"


def producer_id(root: Path, producer: str) -> str:
    return content_id(root, PRODUCER_INPUTS[producer])


def verify_oracle(lock_path: Path, expected_producer: str, oracle_path: Path) -> None:
    _, contents = load_lock(lock_path)
    try:
        oracle = json.loads(oracle_path.read_bytes())
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise ValueError(f"Cannot verify frontend oracle {oracle_path}: expected UTF-8 JSON.") from error
    if not isinstance(oracle, dict):
        raise ValueError(f"Cannot verify frontend oracle {oracle_path}: expected a JSON object.")
    if oracle.get("reference_lock") != lock_id(contents):
        raise ValueError(f"Cannot use frontend oracle {oracle_path}: it was generated from a different reference lock.")
    if oracle.get("reference_build") != expected_producer:
        raise ValueError(f"Cannot use frontend oracle {oracle_path}: it was generated by a different reference producer.")


def main() -> None:
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest="command", required=True)
    values = subparsers.add_parser("values")
    values.add_argument("lock", type=Path)
    identity = subparsers.add_parser("id")
    identity.add_argument("lock", type=Path)
    producer = subparsers.add_parser("producer-id")
    producer.add_argument("producer", choices=tuple(PRODUCER_INPUTS))
    producer.add_argument("root", type=Path)
    image = subparsers.add_parser("image-id")
    image.add_argument("root", type=Path)
    oracle = subparsers.add_parser("verify-oracle")
    oracle.add_argument("lock", type=Path)
    oracle.add_argument("producer_id")
    oracle.add_argument("oracle", type=Path)
    args = parser.parse_args()

    if args.command == "values":
        document, _ = load_lock(args.lock)
        print(document["node_image"])
        print(document["revision"])
    elif args.command == "id":
        _, contents = load_lock(args.lock)
        print(lock_id(contents))
    elif args.command == "producer-id":
        load_lock(args.root / LOCK_RELATIVE_PATH)
        print(producer_id(args.root, args.producer))
    elif args.command == "image-id":
        load_lock(args.root / LOCK_RELATIVE_PATH)
        print(content_id(args.root, IMAGE_INPUTS))
    else:
        verify_oracle(args.lock, args.producer_id, args.oracle)


if __name__ == "__main__":
    main()
