[archive]
record = "https://zenodo.org/records/14638782"
url = "https://zenodo.org/records/14638782/files/zenodo_secs_v3.tar.gz?download=1"
md5 = "5ca6bed3fb7e70630020f55796fd26ab"
member = "MoleculeBindZenodo/app-cpu/checkpoints/residual_augment_resolution_physics_finetune_20250708_1747/best_model.ckpt"

[conversion]
precision = "bfloat16"

[data]
central_modality = "smiles"
modalities = ["h_nmr"]

[model.encoders.smiles]
name = "molformer"
pretrained = false
freeze_encoder = false

[model.encoders.h_nmr]
name = "cnn"
freeze_encoder = false
scale = "xlarge"
use_initial_residual = true

[model.projection_heads]
smiles_is_on = true
smiles_freeze = false
h_nmr_is_on = true
h_nmr_freeze = false

[model.projection_heads.smiles]
dims = [768, 1024]
activation = "LeakyReLU"

[model.projection_heads.h_nmr]
dims = [1024, 1024]
activation = "LeakyReLU"
